2024-11-20 22:15:26,170 - WARNING - Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\ProjectsForUniversity\module_12_4\main.py", line 72, in test_run
    runner = Runner(5)
             ^^^^^^^^^
  File "C:\Users\Admin\Desktop\ProjectsForUniversity\module_12_4\main.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-20 22:15:26,171 - WARNING - Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\ProjectsForUniversity\module_12_4\main.py", line 61, in test_walk
    runner = Runner("Ivan")
             ^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\ProjectsForUniversity\module_12_4\main.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
